-- INCLUSÃO DO CAMPO EXCLUIDOS NAS TABELAS ABAIXO.
-- SCRIPT DE ATUALIZAÇÃO
--
-- CASO O BANCO ESTEJA VAZIO NÃO É NECESSÁRIO ESTE ARQUIVO

ALTER TABLE cltb_cliente ADD COLUMN excluido bool DEFAULT(false);
ALTER TABLE cbtb_cliente_produto ADD COLUMN excluido bool DEFAULT(false);